/**
 * Automatically translated from C++ to Java
 * 
 * Original file: Main.cpp
 * Module: Main
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import jakarta.jms.Connection;
import jakarta.jms.ConnectionFactory;
import jakarta.jms.JMSException;
import jakarta.jms.Message;
import jakarta.jms.MessageConsumer;
import jakarta.jms.Session;
import jakarta.jms.TextMessage;
import com.ibm.mq.jms.MQConnectionFactory;
import com.ibm.mq.jms.MQQueue;
import com.ibm.mq.jms.MQQueueConnectionFactory;

@SpringBootApplication
public class Main {

    public static void main(String[] args) {
        SpringApplication.run(Main.class, args);
        try {
            MQConnectionFactory connectionFactory = new MQQueueConnectionFactory();
            connectionFactory.setHostName("localhost");
            connectionFactory.setPort(1414);
            connectionFactory.setQueueManager("QM1");
            connectionFactory.setChannel("DEV.APP.SVRCONN");

            Connection connection = connectionFactory.createConnection();
            connection.start();

            Session session = connection.createSession(false, Session.AUTO_ACKNOWLEDGE);
            MQQueue queue = new MQQueue("QUEUE1");
            MessageConsumer consumer = session.createConsumer(queue);

            Message message = consumer.receive(1000);
            if (message instanceof TextMessage) {
                TextMessage textMessage = (TextMessage) message;
                System.out.println("Received: " + textMessage.getText());
            }

            consumer.close();
            session.close();
            connection.close();
        } catch (JMSException e) {
            e.printStackTrace();
        }
    }
}