/**
 * Automatically translated from C++ to Java
 * 
 * Original file: Main.cpp
 * Module: Main
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println("Enter two numbers:");
        double num1 = scanner.nextDouble();
        double num2 = scanner.nextDouble();
        
        double result = add(num1, num2);
        System.out.println("The sum is: " + result);
        
        scanner.close();
    }

    public static double add(double a, double b) {
        return a + b;
    }
}