/**
 * Automatically translated from C++ to Java
 * 
 * Original file: include\MathLib.hpp
 * Module: include\MathLib
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

public class MathLib {

    public static int add(int a, int b) {
        return a + b;
    }

    public static int multiply(int a, int b) {
        return a * b;
    }

    public static void main(String[] args) {
        int sum = add(5, 3);
        int product = multiply(5, 3);
        System.out.println("Sum: " + sum);
        System.out.println("Product: " + product);
    }
}