/**
 * Automatically translated from C++ to Java
 * 
 * Original file: include\MathLib.h
 * Module: include\MathLib
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.example.mathlib;

public class MathLib {

    public static int add(int a, int b) {
        return a + b;
    }

    public static int multiply(int a, int b) {
        return a * b;
    }
}