/**
 * Automatically translated from C++ to Java
 * 
 * Original file: src\MathLib.cpp
 * Module: src\MathLib
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

```java
package src;

import jakarta.jms.JMSException;
import jakarta.jms.Message;
import jakarta.jms.Session;
import jakarta.jms.TextMessage;
import com.ibm.mq.jms.MQQueueConnectionFactory;
import com.ibm.mq.jms.MQQueue;
import com.ibm.mq.jms.MQQueueSender;
import com.ibm.mq.jms.MQQueueSession;
import com.ibm.mq.jms.MQQueueConnection;

public class MathLib {

    public int add(int a, int b) {
        return a + b;
    }

    public int subtract(int a, int b) {
        return a - b;
    }

    public int multiply(int a, int b) {
        return a * b;
    }

    public double divide(int a, int b) throws ArithmeticException {
        if (b == 0) {
            throw new ArithmeticException("Division by zero");
        }
        return (double) a / b;
    }

    public void sendMessage(String queueName, String messageContent) throws JMSException {
        MQQueueConnectionFactory factory = new MQQueueConnectionFactory();
        MQQueueConnection connection = (MQQueueConnection) factory.createQueueConnection();
        MQQueueSession session = (MQQueueSession) connection.createQueueSession(false, Session.AUTO_ACKNOWLEDGE);
        MQQueue queue = (MQQueue) session.createQueue(queueName);
        MQQueueSender sender = (MQQueueSender) session.createSender(queue);
        TextMessage message = session.createTextMessage(messageContent);
        sender.send(message);
        sender.close();
        session.close();
        connection.close();
    }
}
```