/**
 * Automatically translated from C++ to Java
 * 
 * Original file: src\MathLib.cpp
 * Module: src\MathLib
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

public class MathLib {

    public static int add(int a, int b) {
        return a + b;
    }

    public static int subtract(int a, int b) {
        return a - b;
    }

    public static int multiply(int a, int b) {
        return a * b;
    }

    public static double divide(int a, int b) {
        if (b == 0) {
            throw new ArithmeticException("Division by zero");
        }
        return (double) a / b;
    }

    public static void main(String[] args) {
        System.out.println("Add: " + add(5, 3));
        System.out.println("Subtract: " + subtract(5, 3));
        System.out.println("Multiply: " + multiply(5, 3));
        System.out.println("Divide: " + divide(5, 3));
    }
}